# Generated by Django 2.2.5 on 2019-09-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productname_40'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttag',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
